chore: add more validations

diff --git a/.github/actions/tests/python/action.yml b/.github/actions/tests/python/action.yml
--- a/.github/actions/tests/python/action.yml
+++ b/.github/actions/tests/python/action.yml
@@ -52,6 +52,34 @@ runs:
             exit 1
           fi
 
+      - name: Check for openai in requirements
+        run: |
+          if ! grep -q "openai" ./requirements.txt; then
+            echo "openai not found in requirements.txt" >&2
+            exit 1
+          fi
+
+      - name: Check for langchain in requirements
+        run: |
+          if ! grep -q "langchain" ./requirements.txt; then
+            echo "langchain not found in requirements.txt" >&2
+            exit 1
+          fi
+
+      - name: Check for langchain-experimental in requirements
+        run: |
+          if ! grep -q "langchain-experimental" ./requirements.txt; then
+            echo "langchain-experimental not found in requirements.txt" >&2
+            exit 1
+          fi
+
+      - name: Check for pinecone-client in requirements
+        run: |
+          if ! grep -q "pinecone-client" ./requirements.txt; then
+            echo "pinecone-client not found in requirements.txt" >&2
+            exit 1
+          fi
+
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
diff --git a/.github/actions/tests/terraform/action.yml b/.github/actions/tests/terraform/action.yml
--- a/.github/actions/tests/terraform/action.yml
+++ b/.github/actions/tests/terraform/action.yml
@@ -37,6 +37,14 @@ runs:
             exit 1
           fi
 
+      - name: Verify Terraform is installed
+        run: |
+          if ! command -v terraform &> /dev/null
+          then
+            echo "Terraform could not be found"
+            exit 1
+          fi
+
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
